// <auto-generated />
using System;
using Gpuviewer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gpuviewer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920130554_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gpuviewer.Models.GraphicsCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .HasColumnType("text");

                    b.Property<double?>("BenchmarkScore")
                        .HasColumnType("double precision");

                    b.Property<double>("BoostClockMhz")
                        .HasColumnType("double precision");

                    b.Property<double>("CoreClockMhz")
                        .HasColumnType("double precision");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MemoryBusWidth")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RtCores")
                        .HasColumnType("integer");

                    b.Property<int?>("ShaderUnits")
                        .HasColumnType("integer");

                    b.Property<int>("TdpWatts")
                        .HasColumnType("integer");

                    b.Property<int?>("TensorCores")
                        .HasColumnType("integer");

                    b.Property<double>("VramGb")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("GraphicsCards");
                });
#pragma warning restore 612, 618
        }
    }
}
